#!/usr/bin/env perl

sub Usage {
    die <<"EOT";
\nUsage: $0 IDFILE FASTAFILE (pair|read) [-v]

$0 prints all entries given by IDFILE which are found in FASTAFILE

EOT
}

&Usage if ($#ARGV < 2);

$idfile = $ARGV[0];
$fastafile = $ARGV[1];
$pair_read = $ARGV[2];
$reverse_matches = $ARGV[3];

if ($reverse_matches eq '-v') {
    $reverse_matches=1;
}
else {
    $reverse_matches=0;
}


open(IDS,$idfile) || die "cannot open IDFILE: $!";
while(<IDS>) {
    chomp;
    $ids{"$_"} = 1;
}
close IDS;


my $entry;

open INFILE,$fastafile or die "Can't open: $fastafile";
$description=<INFILE>;
while ($in = <INFILE>) {
    unless ($in =~ /^>\S+/) {
	$entry .= $in;
    }
    else {
#	$seqnum++;
#	unless ($seqnum % 1000000) {
#	    print STDERR "$seqnum seqs read...\n";
#	}

	if ($pair_read eq "pair") {
	    if ($description =~ /^>(.*)\/\d+/) {
		$pair=$1;
	    }
	    else {
		$pair='';
	    }
	}
	elsif ($pair_read eq "read") {
	    if ($description =~ /^>(\S+)/) {
		$pair=$1;
	    }
	    else {
		$pair='';
	    }
	}
	else {
	    die "please specify if you want to grep for pairs or reads";
	}

	if (exists $ids{$pair} && !$reverse_matches) {
	    print $description.$entry;
	}
	elsif (!exists($ids{$pair}) && $reverse_matches) {
	    print $description.$entry;
	}

	$description=$in;
	$entry="";
    }
}

close INFILE;

#print STDERR "file closed\n";

# check last entry

if ($pair_read eq "pair") {
    if ($description =~ /^>(.*)\/\d+/) {
	$pair=$1;
    }
    else {
	$pair='';
    }
}
elsif ($pair_read eq "read") {
    if ($description =~ /^>(\S+)/) {
	$pair=$1;
    }
    else {
	$pair='';
    }
}

if (exists $ids{$pair} && !$reverse_matches) {
    print $description.$entry;
}
elsif (!exists($ids{$pair}) && $reverse_matches) {
    print $description.$entry;
}

